name: learn-github-actions
on: [push]
jobs:
  multi:
    runs-on: ubuntu-latest
    env:
        FUSIONAUTH_VERSION: 1.20.0
    steps:
      - 
        name: identify
        run: echo ${{ env.FUSIONAUTH_VERSION }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        env:
          FUSIONAUTH_VERSION: 1.20.0
        with:
          context: .
          file: ./Dockerfile
          build-args: FUSIONAUTH_VERSION=${{ env.FUSIONAUTH_VERSION }}
          args: FUSIONAUTH_VERSION=${{ env.FUSIONAUTH_VERSION }}
          platforms: linux/amd64
          push: false
          tags: |
            jerryhopper/demo-multiarch:latest
            jerryhopper/demo-multiarch:${{ env.FUSIONAUTH_VERSION }}
